name = ""
main = "src/index.ts"
compatibility_date = "2025-01-18"

# compatibility_flags = [ "nodejs_compat" ]

[vars]

[[kv_namespaces]]
binding = "FIREBASE_PUBLIC_JWK_CACHE_KV"
id = "${FIREBASE_PUBLIC_JWK_CACHE_KV_ID}"

# [[r2_buckets]]
# binding = "MY_BUCKET"
# bucket_name = "my-bucket"

[[d1_databases]]
binding = "DB"
database_name = "${DATABASE_NAME}"
database_id = "${DATABASE_ID}"

# [ai]
# binding = "AI"

# [observability]
# enabled = true
# head_sampling_rate = 1

[observability.logs]
enabled = true
