name = "payment_service"
main = "src/index.ts"
compatibility_date = "2025-01-18"

# compatibility_flags = [ "nodejs_compat" ]

[vars]
API_KEY=""
ADMIN_API_KEY=""
ITEM_API_URL=""
CONSUMER_SITE_BASE_URL=""
RESEND_API_KEY=""

# [[kv_namespaces]]
# binding = "MY_KV_NAMESPACE"
# id = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"

# [[r2_buckets]]
# binding = "MY_BUCKET"
# bucket_name = "my-bucket"

[[d1_databases]]
binding = "DB"
database_name = "${DATABASE_NAME}"
database_id = "${DATABASE_ID}"

# [ai]
# binding = "AI"

# [observability]
# enabled = true
# head_sampling_rate = 1
